### PR TITLE
FEAT: Add missing information in regard to class configuraton on assemblers

### LINKED ISSUE #79: Add class configuration section to assemblers
The assemblers page is missing information about how to configure a default assembler:

```
classes:
  org:
    generated:
      project:
        defaultAssembler: ...
```

Use the same form as in http://seedstack.org/docs/business/repositories/#class-configuration

### PR DESCRIPTION
**Pull request by Sherpard**

### CODE REVIEW

**Comment by Sherpard** [comment]
BTW, I was unable to launch hugo locally, so I cannot confirm that this addition works as intended

**Comment by adrienlauer** [comment]
Closes #79

**Comment by adrienlauer** [comment]
Thanks @Sherpard for the great help !

**Review by adrienlauer — COMMENTED** [review]
Perfect

**Pull request merged**
